baseURL = "https://arcticsquall.com/"
languageCode = "en-us"
title = "Arctic Squall Games"
theme = "ananke"
sectionPagesMenu = "main"
Paginate = 3
mainSections = ["post", "onepagers"]
metaDataFormat = "yaml"

[params]
    twitter = "https://twitter.com/ArcticSquall"
    instagram = "https://instagram.com/ArcticSquall"
    facebook = "https://www.facebook.com/groups/arcticsquallgames/"
